package ru.alejov.util.stime;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Ovcharov Alexey
 */
public class ReportForm extends javax.swing.JDialog {

    private List<List<String>> data = new ArrayList<>();

    /**
     * Creates new form ReportForm
     * @param parent
     * @param modal
     */
    public ReportForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        AbstractTableModel abstractTableModel = new AbstractTableModel() {
            @Override
            public int getRowCount() {
                return data.size();
            }

            @Override
            public int getColumnCount() {
                return 2;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                return data.get(rowIndex).get(columnIndex);
            }
        };
        tableReport.setModel(abstractTableModel);
        JTableHeader tableHeader = tableReport.getTableHeader();
        TableColumnModel columnModel = tableHeader.getColumnModel();
        TableColumn column0 = columnModel.getColumn(0);
        
        int column0Width = tableHeader.getWidth() * 75 / 100;
        column0.setHeaderValue("TaskId");
        column0.setPreferredWidth(column0Width);
        column0.setWidth(column0Width);
        
        int column1Width = tableHeader.getWidth() * 25 / 100;
        TableColumn column1 = columnModel.getColumn(1);
        column1.setHeaderValue("Time");
        column1.setPreferredWidth(column1Width);
        column1.setWidth(column1Width);
    }

    void setRep(List<List<String>> data) {
        this.data = data;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneReport = new javax.swing.JScrollPane();
        tableReport = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));

        tableReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Track", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPaneReport.setViewportView(tableReport);

        getContentPane().add(scrollPaneReport, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPaneReport;
    private javax.swing.JTable tableReport;
    // End of variables declaration//GEN-END:variables

}
